<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-19T11:32:31 IST" name="Suite" finished-at="2025-08-19T11:34:22 IST" duration-ms="110562">
    <groups>
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Tests.SubmitOrderTest@7776ab]" name="submitOrder" class="Tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
      <group name="Errorhandling">
        <method signature="ErrorValidation.submitOrder()[pri:0, instance:Tests.ErrorValidation@38831718]" name="submitOrder" class="Tests.ErrorValidation"/>
      </group> <!-- Errorhandling -->
    </groups>
    <test started-at="2025-08-19T11:32:31 IST" name="Test" finished-at="2025-08-19T11:34:22 IST" duration-ms="110562">
      <class name="Tests.SubmitOrderTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:32:32 IST" name="setUp" finished-at="2025-08-19T11:32:34 IST" duration-ms="2039" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:32:34 IST" name="submitOrder" data-provider="getData" finished-at="2025-08-19T11:33:14 IST" duration-ms="40692" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Product=ADIDAS ORIGINAL, password=Adhish@123, email=adhish16singh@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:15 IST" name="tearDown" finished-at="2025-08-19T11:33:15 IST" duration-ms="194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:15 IST" name="setUp" finished-at="2025-08-19T11:33:16 IST" duration-ms="1250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:16 IST" name="submitOrder" data-provider="getData" finished-at="2025-08-19T11:33:40 IST" duration-ms="23646" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Product=ZARA COAT 3, password=Adhish@123, email=adhish16singh@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:40 IST" name="tearDown" finished-at="2025-08-19T11:33:40 IST" duration-ms="101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:40 IST" name="setUp" finished-at="2025-08-19T11:33:41 IST" duration-ms="1003" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:41 IST" name="OrderHistoryTest" finished-at="2025-08-19T11:33:43 IST" depends-on-methods="Tests.SubmitOrderTest.submitOrder" duration-ms="1299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.SubmitOrderTest@7776ab]" started-at="2025-08-19T11:33:43 IST" name="tearDown" finished-at="2025-08-19T11:33:43 IST" duration-ms="94" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.SubmitOrderTest -->
      <class name="Tests.ErrorValidation">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:33:43 IST" name="setUp" finished-at="2025-08-19T11:33:44 IST" duration-ms="922" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:33:44 IST" name="ProductErrorValidation" finished-at="2025-08-19T11:34:16 IST" duration-ms="31410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:16 IST" name="tearDown" finished-at="2025-08-19T11:34:16 IST" duration-ms="110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:16 IST" name="setUp" finished-at="2025-08-19T11:34:17 IST" duration-ms="1019" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="submitOrder()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:17 IST" name="submitOrder" finished-at="2025-08-19T11:34:19 IST" duration-ms="1240" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect emasil or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect emasil or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Tests.ErrorValidation.submitOrder(ErrorValidation.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:19 IST" name="tearDown" finished-at="2025-08-19T11:34:19 IST" duration-ms="83" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:19 IST" name="setUp" finished-at="2025-08-19T11:34:20 IST" duration-ms="949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="submitOrder()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:20 IST" name="submitOrder" finished-at="2025-08-19T11:34:21 IST" duration-ms="1505" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect emasil or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect emasil or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Tests.ErrorValidation.submitOrder(ErrorValidation.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.ErrorValidation@38831718]" started-at="2025-08-19T11:34:22 IST" name="tearDown" finished-at="2025-08-19T11:34:22 IST" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.ErrorValidation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
